<?xml version="1.0" encoding="UTF-8"?>

<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>edu.robson</groupId>
    <artifactId>experiments-java</artifactId>
    <version>1.0.0-SNAPSHOT</version>
    <packaging>pom</packaging>
    <name>experiments-java : parent</name>
    <description>Programming experiments with Java - parent</description>
    <url>https://github.com/rdubisz/experiments-java</url>

    <properties>
        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
        <project.reporting.outputEncoding>UTF-8</project.reporting.outputEncoding>
        <java.version>25</java.version>
        <!-- Maven plugins -->
        <maven.compiler.source>${java.version}</maven.compiler.source>
        <maven.compiler.target>${java.version}</maven.compiler.target>
        <maven-compiler-plugin.version>3.14.0</maven-compiler-plugin.version>
        <maven-resources-plugin.version>3.3.1</maven-resources-plugin.version>
        <maven-download-plugin.version>2.0.0</maven-download-plugin.version>
        <maven-antrun-plugin.version>3.1.0</maven-antrun-plugin.version>
        <maven-surefire-plugin.version>3.5.4</maven-surefire-plugin.version>
        <maven-docker-plugin.version>0.46.0</maven-docker-plugin.version>
        <maven-dependency-check-plugin.version>12.1.6</maven-dependency-check-plugin.version>
        <!-- Libraries -->
        <logback.version>1.5.19</logback.version>
        <slf4j.version>2.0.17</slf4j.version>
        <annotation-api.version>2.1.1</annotation-api.version>
        <persistence-api.version>3.1.0</persistence-api.version>
        <validation-api.version>3.1.1</validation-api.version>
        <commons-lang3.version>3.19.0</commons-lang3.version>
        <flyway.version>11.13.3</flyway.version>
        <h2.version>2.4.240</h2.version>
        <mariadb-connector.version>3.5.6</mariadb-connector.version>
        <commons-dbcp2.version>2.13.0</commons-dbcp2.version>
        <httpclient.version>5.5.1</httpclient.version>

        <!-- Test dependencies -->
        <junit.version>6.0.1</junit.version>
        <assertj.version>3.27.6</assertj.version>
        <mockito.version>5.20.0</mockito.version>
        <testcontainers.version>1.21.3</testcontainers.version>

        <!-- Template variables -->
        <docker.app.dir>/opt/app</docker.app.dir>
        <docker.autoCreateCustomNetworks>true</docker.autoCreateCustomNetworks>
    </properties>

    <scm>
        <connection>scm:git:https://github.com/rdubisz/experiments.git</connection>
        <url>https://github.com/rdubisz/experiments</url>
    </scm>

    <repositories>
        <repository>
            <id>maven_central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </repository>
        <repository>
            <id>vaadin-prereleases</id>
            <name>Vaadin Pre-release Repository</name>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
        </repository>
        <repository>
            <id>vaadin-addons-directory</id>
            <name>Vaadin Addons Directory</name>
            <url>https://maven.vaadin.com/vaadin-addons</url>
            <snapshots>
                <enabled>false</enabled>
            </snapshots>
        </repository>
    </repositories>

    <pluginRepositories>
        <pluginRepository>
            <id>maven_central</id>
            <name>Central Repository</name>
            <url>https://repo.maven.apache.org/maven2</url>
        </pluginRepository>
        <pluginRepository>
            <id>vaadin-prereleases</id>
            <name>Vaadin Pre-release Repository</name>
            <url>https://maven.vaadin.com/vaadin-prereleases/</url>
        </pluginRepository>
    </pluginRepositories>

    <modules>
        <module>experiments-common</module>
        <module>experiments-java-8</module>
        <module>experiments-java-11</module>
        <module>experiments-java-17</module>
        <module>experiments-java-21</module>
    </modules>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-classic</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>ch.qos.logback</groupId>
                <artifactId>logback-core</artifactId>
                <version>${logback.version}</version>
            </dependency>
            <dependency>
                <groupId>org.slf4j</groupId>
                <artifactId>slf4j-api</artifactId>
                <version>${slf4j.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.httpcomponents.client5</groupId>
                <artifactId>httpclient5</artifactId>
                <version>${httpclient.version}</version>
            </dependency>
            <dependency>
                <groupId>org.mariadb.jdbc</groupId>
                <artifactId>mariadb-java-client</artifactId>
                <version>${mariadb-connector.version}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-core</artifactId>
                <version>${flyway.version}</version>
            </dependency>
            <dependency>
                <groupId>org.flywaydb</groupId>
                <artifactId>flyway-mysql</artifactId>
                <version>${flyway.version}</version>
            </dependency>
            <dependency>
                <groupId>org.jooq</groupId>
                <artifactId>jooq</artifactId>
                <version>${jooq.version}</version>
            </dependency>

            <!-- Test dependencies -->
            <dependency>
                <groupId>org.junit</groupId>
                <artifactId>junit-bom</artifactId>
                <version>6.0.1</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>

    <build>
        <pluginManagement>
            <plugins>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-compiler-plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-resources-plugin</artifactId>
                    <version>${maven-resources-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-antrun-plugin</artifactId>
                    <version>${maven-antrun-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-surefire-plugin</artifactId>
                    <version>${maven-surefire-plugin.version}</version>
                    <configuration>
                        <parallel>classes</parallel>
                        <threadCount>5</threadCount>
                    </configuration>
                    <dependencies>
                        <dependency>
                            <groupId>org.junit.jupiter</groupId>
                            <artifactId>junit-jupiter-engine</artifactId>
                            <version>${junit.version}</version>
                        </dependency>
                        <dependency>
                            <groupId>org.junit.platform</groupId>
                            <artifactId>junit-platform-launcher</artifactId>
                            <version>6.0.1</version>
                        </dependency>
                    </dependencies>
                </plugin>
                <!--            <plugin>-->
                <!--                <groupId>org.apache.maven.plugins</groupId>-->
                <!--                <artifactId>maven-failsafe-plugin</artifactId>-->
                <!--                <version>${maven-surefire-plugin.version}</version>-->
                <!--            </plugin>-->
                <!--            <plugin>-->
                <!--                <groupId>org.apache.maven.plugins</groupId>-->
                <!--                <artifactId>maven-surefire-report-plugin</artifactId>-->
                <!--                <version>${maven-surefire-plugin.version}</version>-->
                <!--            </plugin>-->
                <plugin>
                    <groupId>io.github.download-maven-plugin</groupId>
                    <artifactId>download-maven-plugin</artifactId>
                    <version>${maven-download-plugin.version}</version>
                </plugin>
                <plugin>
                    <groupId>io.fabric8</groupId>
                    <artifactId>docker-maven-plugin</artifactId>
                    <version>${maven-docker-plugin.version}</version>
                </plugin>

            </plugins>
        </pluginManagement>
    </build>

    <profiles>
        <profile>
            <id>code-reports</id>
            <build>
                <plugins>
                    <plugin>
                        <groupId>org.owasp</groupId>
                        <artifactId>dependency-check-maven</artifactId>
                        <version>${maven-dependency-check-plugin.version}</version>
                        <configuration>
                            <!-- Disable .NET check -->
                            <assemblyAnalyzerEnabled>false</assemblyAnalyzerEnabled>
                        </configuration>
                        <executions>
                            <execution>
                                <goals>
                                    <goal>check</goal>
                                </goals>
                            </execution>
                        </executions>
                    </plugin>
                </plugins>
            </build>
        </profile>
    </profiles>

</project>
